# Image
FROM mcr.microsoft.com/devcontainers/base:alpine

# Install the basics
RUN apk add --no-cache \
    bash bash-completion fish \
    git openssh-client curl

# Install host-spawn
RUN curl -fsSL \
    https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64 \
    -o /usr/local/bin/host-spawn

# copy setup scripts
COPY setup/setup-java /usr/local/bin/
COPY setup/setup-rust /usr/local/bin/
RUN chmod +x /usr/local/bin/*
    
# Switch to user
#USER root
