# Image
FROM docker.io/library/eclipse-temurin:8-alpine

# Install the basics
RUN apk add --no-cache \
    bash bash-completion \
    fish fish-completion \
    git openssh-client curl \
    && \
    curl -fsSL \
    https://github.com/1player/host-spawn/releases/latest/download/host-spawn-x86_64 \
    -o /usr/local/bin/host-spawn
    
# Switch to user
USER root